version: '3.8'

services:
  upload-service:
    build: ./upload_service
    ports:
      - "50051:50051"
    env_file:
      - ./upload_service/.env
    depends_on:
      - redis
      - minio

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data

volumes:
  minio-data: