# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upload.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'upload.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cupload.proto\x12\x06upload\"^\n\x12ImageUploadRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\"7\n\x13ImageUploadResponse\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2W\n\rUploadService\x12\x46\n\x0bUploadImage\x12\x1a.upload.ImageUploadRequest\x1a\x1b.upload.ImageUploadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEUPLOADREQUEST']._serialized_start=24
  _globals['_IMAGEUPLOADREQUEST']._serialized_end=118
  _globals['_IMAGEUPLOADRESPONSE']._serialized_start=120
  _globals['_IMAGEUPLOADRESPONSE']._serialized_end=175
  _globals['_UPLOADSERVICE']._serialized_start=177
  _globals['_UPLOADSERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)
