# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: filter.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'filter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66ilter.proto\x12\napi.filter\"\x8a\x01\n\rFilterRequest\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x37\n\x07\x66ilters\x18\x02 \x03(\x0b\x32&.api.filter.FilterRequest.FiltersEntry\x1a.\n\x0c\x46iltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"&\n\x0e\x46ilterResponse\x12\x14\n\x0c\x66iltered_url\x18\x01 \x01(\t2V\n\rFilterService\x12\x45\n\x0c\x41pplyFilters\x12\x19.api.filter.FilterRequest\x1a\x1a.api.filter.FilterResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'filter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILTERREQUEST_FILTERSENTRY']._loaded_options = None
  _globals['_FILTERREQUEST_FILTERSENTRY']._serialized_options = b'8\001'
  _globals['_FILTERREQUEST']._serialized_start=29
  _globals['_FILTERREQUEST']._serialized_end=167
  _globals['_FILTERREQUEST_FILTERSENTRY']._serialized_start=121
  _globals['_FILTERREQUEST_FILTERSENTRY']._serialized_end=167
  _globals['_FILTERRESPONSE']._serialized_start=169
  _globals['_FILTERRESPONSE']._serialized_end=207
  _globals['_FILTERSERVICE']._serialized_start=209
  _globals['_FILTERSERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
